'use client';
import {useState} from 'react';
import Link from 'next/link';
import {ArrowUpRight,ArrowDown} from 'lucide-react';
import {Accordion,AccordionContent,AccordionItem,AccordionTrigger} from '@/components/ui/accordion';
import {Reveal} from './motion';
const chapters=[
 {id:'place',word:'The place.',title:'Start with the setting.',text:'A storefront, a reception wall or a printed introduction each has a different job. Share where your brand needs to appear and what people should notice.',bring:'Site photographs, approximate sizes and the purpose of the project.',link:'/solutions',linkText:'Explore business settings'},
 {id:'detail',word:'The details.',title:'Give the idea a specification.',text:'Size, material, quantity and finish shape the result. Discuss the available options and get the scope documented for your particular project.',bring:'Your logo, quantities, material references and any site restrictions.',link:'/signage',linkText:'Explore signs and materials'},
 {id:'artwork',word:'The artwork.',title:'Check what people will see.',text:'Names, contact details, colours and dimensions all deserve a careful review. Keep an editable original and share the final wording with your brief.',bring:'Logo artwork, copy and a clear review file.',link:'/ideas/artwork-checklist',linkText:'Read the artwork checklist'},
 {id:'plan',word:'The plan.',title:'Bring the practical pieces together.',text:'Share the required date, delivery location and access details. Production timing, delivery and any installation requirements are confirmed for your project.',bring:'Your timing, location, permissions and installation needs.',link:'/contact',linkText:'Talk through your project'}
];
export function AboutExperience(){const [chapter,setChapter]=useState('place');const active=chapters.findIndex(c=>c.id===chapter);
 return <main id="main" className="about-experience">
  <section className="about-story-opening wrap"><div className="about-story-title"><p className="eyebrow">About SignAds / Advertising. Printing. Signages.</p><h1>Ideas become<br/><em>physical things.</em></h1><p className="about-story-deck">A card in a hand. A name above a door. A message moving through the city.</p><p>SignAds brings print, signage, fabrication and outdoor advertising into the places where people meet your brand.</p><a className="text-link" href="#about-approach">See how a project takes shape <ArrowDown size={18}/></a></div><figure className="about-director"><div className="about-portrait-frame"><img src="/images/founder-portrait.webp" alt="Nitesh Telange, Managing Director of SignAds" width="560" height="578" fetchPriority="high"/></div><figcaption><span><strong>Nitesh Telange</strong><small>Managing Director, SignAds</small></span><span className="about-portrait-mark" aria-hidden="true">S/</span></figcaption></figure></section>
  <section className="about-belief"><Reveal className="wrap about-belief-layout"><p className="eyebrow">The work connects</p><div><h2>From the smallest card<br/>to the <em>biggest impression.</em></h2><p>Print gives people something to keep. Signage makes a place recognisable. Outdoor formats carry a message further. The starting point is the same: what does your brand need to say, and where does it need to be seen?</p></div></Reveal></section>
  <section className="about-materials wrap"><figure><img src="/images/about-materials.webp" alt="Illustrative material study with printed stationery, dimensional metal letters and orange acrylic samples on a worktable" width="1536" height="1024" loading="lazy"/><figcaption><span>Paper. Colour. Metal. Light.</span><span>Illustrative material study</span></figcaption></figure><div className="about-material-links">{[{n:'01',title:'Something to hold.',text:'Visiting cards, flyers, brochures and banners.',href:'/print-products',label:'Print & paper'},{n:'02',title:'A place to belong.',text:'Lettering, illuminated signs and architectural surfaces.',href:'/signage',label:'Signage & fabrication'},{n:'03',title:'A message that moves.',text:'Vehicle branding and outdoor campaign formats.',href:'/outdoor',label:'Outdoor & transit'}].map(s=><Link key={s.n} href={s.href}><span className="about-capability-label">{s.n} / {s.label}</span><h3>{s.title}</h3><p>{s.text}</p><ArrowUpRight size={24}/></Link>)}</div></section>
  <section id="about-approach" className="about-approach"><div className="wrap about-approach-grid"><div className="about-approach-intro"><p className="eyebrow">From a thought to a brief</p><h2>Good work starts<br/><em>with clarity.</em></h2><p>Four conversations that help turn an idea into a useful project brief.</p><div className="about-chapter-mark" aria-hidden="true"><span key={chapter}>0{active+1}</span><small>{chapters[active]?.word}</small></div><div className="about-chapter-progress" aria-hidden="true">{chapters.map((c,i)=><span className={i<=active?'on':''} key={c.id}/>)}</div></div><Accordion type="single" value={chapter} onValueChange={value=>{if(value)setChapter(value)}} className="about-chapters">{chapters.map((c,i)=><AccordionItem key={c.id} value={c.id}><AccordionTrigger><span className="about-chapter-number">0{i+1}</span><span>{c.title}</span></AccordionTrigger><AccordionContent><p>{c.text}</p><div className="about-bring"><span>Useful to bring</span><p>{c.bring}</p></div><Link href={c.link} className="text-link">{c.linkText}<ArrowUpRight size={17}/></Link></AccordionContent></AccordionItem>)}</Accordion></div></section>
  <Reveal className="about-invitation wrap"><p className="eyebrow">Your brand, out in the world</p><h2>Bring the idea.<br/><em>Let’s talk about the making.</em></h2><div><p>Have a photograph, a rough size or a first thought? That’s a useful place to begin.</p><Link href="/contact" className="button">Start a conversation <ArrowUpRight size={19}/></Link></div><Link className="text-link" href="/work">See the work in real settings <ArrowUpRight size={18}/></Link></Reveal>
 </main>
}
