'use client';
import {useState} from 'react';
import Link from 'next/link';
import {ArrowUpRight,ArrowRight} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Content,hrefFor} from '@/lib/content';
const goals=[
 {id:'hand',label:'Hand it out',title:'A little paper. A lasting introduction.',text:'Choose a format for the message people take away.',image:'/images/print-scenes/flyers-pamphlets.webp',alt:'Illustrative printed flyers and folded pamphlets on a café counter',caption:'Illustrative print scene',services:['visiting-cards','flyers-pamphlets','brochures','banners'],href:'/print-products',link:'Explore print products',brief:'Print materials'},
 {id:'space',label:'Brand a space',title:'Give your name a place to belong.',text:'Shape the first impression with lettering, light and surfaces.',image:'/images/solution-scenes/offices-receptions.webp',alt:'Illustrative office reception with dimensional identity lettering',caption:'Illustrative reception scene',services:['dimensional-letters','led-signboards','acp-cladding','glow-signs'],href:'/signage',link:'Explore signage',brief:'Signage for my space'},
 {id:'street',label:'Reach the street',title:'Take your message beyond the door.',text:'Find a format for the route, location and campaign you have in mind.',image:'/images/hoarding-product.webp',alt:'Illustrative roadside advertising hoarding on steel supports',caption:'Illustrative outdoor display',services:['vehicle-branding','hoardings','banners'],href:'/outdoor',link:'Explore outdoor formats',brief:'Outdoor campaign'},
 {id:'guide',label:'Guide visitors',title:'Make the next step easy to find.',text:'Help people recognise the entrance, choose a route and reach their destination.',image:'/images/solution-scenes/safety-directional.webp',alt:'Illustrative building lobby with directory and directional signs',caption:'Illustrative wayfinding scene',services:['wayfinding','dimensional-letters'],href:'/services/wayfinding',link:'Explore wayfinding',brief:'Wayfinding and destination signs'}
];
export function HomeFormatFinder({products}:{products:Content[]}){const [active,setActive]=useState('hand');return <section className="home-format-finder wrap" id="explore"><header className="home-finder-heading"><div><p className="eyebrow">Find your format</p><h2>What do you want<br/><em>your brand to do?</em></h2></div><p>Start with the purpose.<br/>Find the print or signage that fits.</p></header><Tabs value={active} onValueChange={setActive} className="home-finder-tabs"><TabsList className="home-goal-list" aria-label="Choose what your brand needs to do">{goals.map((g,i)=><TabsTrigger key={g.id} value={g.id} className="home-goal"><span>0{i+1}</span>{g.label}<ArrowUpRight size={17}/></TabsTrigger>)}</TabsList>{goals.map(g=><TabsContent key={g.id} value={g.id} className="home-goal-panel"><figure className="home-goal-image"><img src={g.image} alt={g.alt} width="1536" height="1024" loading="lazy"/><figcaption>{g.caption}</figcaption></figure><div className="home-goal-detail"><h3>{g.title}</h3><p>{g.text}</p><ul>{g.services.map(id=>{const p=products.find(p=>p.id===id);return p?<li key={id}><Link href={hrefFor(p)}><span>{p.title}</span><ArrowUpRight size={17}/></Link></li>:null})}</ul><div className="home-goal-actions"><Link href={g.href} className="home-goal-browse">{g.link}<ArrowRight size={17}/></Link><Link href={`/contact?service=${encodeURIComponent(g.brief)}`} className="home-goal-enquire">Discuss a brief</Link></div></div></TabsContent>)}</Tabs></section>}
