"use client";
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {Search,SlidersHorizontal,Expand,ArrowUpRight,ArrowLeft,ArrowRight} from 'lucide-react';
import {Content,hrefFor,imageUrl} from '@/lib/content';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Collapsible,CollapsibleContent,CollapsibleTrigger} from '@/components/ui/collapsible';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {DayNight} from './motion';
export function Choice({label,value,onChange,options,id}:{label:string;value:string;onChange:(s:string)=>void;options:string[];id?:string}){return <div className="choice"><label id={`${id||label}-label`}>{label}</label><Select value={value} onValueChange={onChange}><SelectTrigger aria-labelledby={`${id||label}-label`}><SelectValue/></SelectTrigger><SelectContent>{options.map(s=><SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent></Select></div>}

export function Portfolio({items}:{items:Content[]}){
 const [query,setQuery]=useState('');const [service,setService]=useState('All services');const [industry,setIndustry]=useState('All industries');const [application,setApplication]=useState('All applications');const [location,setLocation]=useState('All locations');
 const [filtersOpen,setFiltersOpen]=useState(false);const [preview,setPreview]=useState<Content|null>(null);const trigger=useRef<HTMLButtonElement|null>(null);
 const categories=['All services',...new Set(items.map(i=>i.category))];const locations=[...new Set(items.map(i=>i.location).filter(Boolean))] as string[];
 const filtered=items.filter(p=>(service==='All services'||p.category===service)&&(industry==='All industries'||p.industry===industry)&&(application==='All applications'||p.application===application)&&(location==='All locations'||p.location===location)&&`${p.title} ${p.category} ${p.description} ${p.industry} ${p.application}`.toLowerCase().includes(query.toLowerCase()));
 const activeFilters=[service!=='All services',industry!=='All industries',application!=='All applications',location!=='All locations'].filter(Boolean).length;
 const clear=()=>{setQuery('');setService('All services');setIndustry('All industries');setApplication('All applications');setLocation('All locations')};
 const position=preview?filtered.findIndex(p=>p.id===preview.id):-1;
 useEffect(()=>{const context=(document as unknown as {modelContext?:{registerTool:(t:unknown,o:unknown)=>Promise<void>}}).modelContext;if(!context)return;const controller=new AbortController();Promise.resolve(context.registerTool({name:'filter_signads_portfolio',title:'Filter SignAds portfolio',description:'Filter the visible portfolio by a service category. Does not submit an enquiry.',inputSchema:{type:'object',properties:{service:{type:'string',enum:categories}},required:['service'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input:unknown){const val=(input as {service?:string})?.service;if(!val||!categories.includes(val))throw new Error('Choose an existing service category');setService(val);setIndustry('All industries');setApplication('All applications');setLocation('All locations');setQuery('');return {service:val,count:items.filter(p=>val==='All services'||p.category===val).length}}},{signal:controller.signal})).catch(()=>{});return()=>controller.abort()},[items]);
 return <div className="portfolio-compact">
  <Collapsible open={filtersOpen} onOpenChange={setFiltersOpen}>
   <div className="portfolio-toolbar"><div className="portfolio-label"><h2>Project gallery</h2><span role="status">{filtered.length} {filtered.length===1?'project':'projects'}</span></div><div className="portfolio-tools"><label className="portfolio-search"><Search size={17} aria-hidden="true"/><input aria-label="Search portfolio" placeholder="Search projects" value={query} onChange={e=>setQuery(e.target.value)}/></label><CollapsibleTrigger className="portfolio-filter-toggle"><SlidersHorizontal size={17} aria-hidden="true"/>Filters{activeFilters>0&&<span>{activeFilters}</span>}</CollapsibleTrigger>{(activeFilters>0||query)&&<button type="button" className="portfolio-reset" onClick={clear}>Reset</button>}</div></div>
   <CollapsibleContent><div className="portfolio-filter-drawer"><Choice label="Service" value={service} onChange={setService} options={categories}/><Choice label="Industry" value={industry} onChange={setIndustry} options={['All industries',...new Set(items.map(i=>i.industry).filter(Boolean))] as string[]}/><Choice label="Application" value={application} onChange={setApplication} options={['All applications',...new Set(items.map(i=>i.application).filter(Boolean))] as string[]}/>{locations.length>0&&<Choice label="Location" value={location} onChange={setLocation} options={['All locations',...locations]}/>}</div></CollapsibleContent>
  </Collapsible>
  {filtered.length?<div className="portfolio-equal-grid">{filtered.map(p=><article key={p.id} className="portfolio-project"><button className="portfolio-photo" type="button" aria-label={`Quick view: ${p.title}`} onClick={e=>{trigger.current=e.currentTarget;setPreview(p)}}><img src={imageUrl(p.image)} alt={p.description} width="900" height="600" loading="lazy"/><span className="portfolio-quick"><Expand size={15} aria-hidden="true"/>Quick view</span>{p.id==='restaurant-day-night'&&<span className="portfolio-daynight-label">Day / night</span>}</button><div className="portfolio-project-meta"><span>{p.category}</span>{p.industry&&<span>{p.industry}</span>}</div><h3><Link href={hrefFor(p)}>{p.title}<ArrowUpRight size={17} aria-hidden="true"/></Link></h3></article>)}</div>:<div className="empty-state"><h3>No matching projects</h3><p>Try a different search or clear your filters.</p><button type="button" className="button" onClick={clear}>Clear filters</button></div>}
  <Dialog open={!!preview} onOpenChange={open=>{if(!open)setPreview(null)}}><DialogContent className="portfolio-preview" onCloseAutoFocus={e=>{e.preventDefault();trigger.current?.focus()}}>{preview&&<><div className="portfolio-preview-heading"><p>{preview.category} / {preview.industry||preview.application}</p><DialogTitle>{preview.title}</DialogTitle><DialogDescription>{preview.description}</DialogDescription></div><div className="portfolio-preview-image">{preview.id==='restaurant-day-night'?<DayNight/>:<img src={imageUrl(preview.image)} alt={preview.description} width="1040" height="700"/>}</div><div className="portfolio-preview-bottom"><div><button type="button" aria-label="Previous project photograph" disabled={position<=0} onClick={()=>setPreview(filtered[position-1])}><ArrowLeft size={19}/></button><span aria-live="polite">{position+1} / {filtered.length}</span><button type="button" aria-label="Next project photograph" disabled={position>=filtered.length-1} onClick={()=>setPreview(filtered[position+1])}><ArrowRight size={19}/></button></div><Link href={hrefFor(preview)}>Project details <ArrowUpRight size={17}/></Link></div></>}</DialogContent></Dialog>
 </div>
}
