export type Content = {id:string;kind:'product'|'project'|'guide';title:string;eyebrow:string;description:string;image:string;category:string;industry?:string;application?:string;body:string[];details:string[];related:string[];images?:string[];assetId?:string;status:'published'|'draft';rightsStatus?:string;origin?:string;clientName?:string;clientApproved?:boolean;location?:string;date?:string};
const product=(id:string,title:string,category:string,description:string,image:string,details:string[],body:string[]):Content=>({id,kind:'product',title,eyebrow:category,category,description,image,details,body,related:[],status:'published'});
const project=(id:string,title:string,category:string,image:string,assetId:string,industry:string,application:string,description:string,related:string[],images?:string[]):Content=>({id,kind:'project',title,eyebrow:'From the profile',category,image,assetId,industry,application,description,related,images,body:['Photographed in the SignAds company profile. The gallery shows the visible application and finish.'],details:[`Application: ${application}`,`Service category: ${category}`],status:'published',rightsStatus:'permission-pending',clientApproved:false,origin:'pdf-extraction'});
export const baseContent:Content[]=[
product('visiting-cards','Visiting cards','Print','A small introduction that leaves something tangible behind.','print-study',['Quantity','Finished size','Single or double sided','Paper and finish preferences'],['Bring your logo, contact details and the quantity you have in mind. We can discuss the right print specification for your brief.','Share any paper, colour or finish references. Available options and the final production specification will be confirmed in your quote.']),
product('flyers-pamphlets','Flyers & pamphlets','Print','Give your next launch, offer or event a clear, portable message.','print-study',['Quantity and distribution plan','Finished size','Single or double sided','Artwork status'],['Start with the one message your reader should take away. Include your offer, location and a clear way to respond.','Send your quantity, dimensions and artwork to discuss the available print options.']),
product('brochures','Brochures','Print','Room to tell the whole story, one fold at a time.','print-study',['Number of pages or panels','Fold preference','Quantity','Paper and artwork requirements'],['Product ranges, company introductions and service information benefit from a clear reading order. Share a draft or a reference brochure with your enquiry.','Folds, stock, binding and production options are subject to confirmation for your project.']),
product('banners','Banners','Print','Put your message where people can see it.','outdoor-branding',['Width and height','Indoor or outdoor use','Mounting location','Needed-by date'],['Tell us where the banner will go, how it will be viewed and the dimensions available.','Artwork, material and finishing requirements depend on the intended placement. Include a photograph of the site when possible.']),
product('led-signboards','LED signboards','Signage','Give your storefront a presence after the sun goes down.','restaurant-night',['Sign dimensions','Day and night visibility','Power access','Wall or fascia photographs'],['The profiles show illuminated shop boards and storefront lettering in several settings. Your enquiry can include a new sign or a replacement for an existing fascia.','Share site photographs, the logo, dimensions and the desired lighting effect. Electrical and installation requirements need a project-specific review.']),
product('acp-cladding','ACP cladding','Signage','Create a considered frame for your storefront or building.','acp-cladding',['Facade dimensions','Existing wall condition','Colour reference','Site access'],['Aluminium composite panel cladding is listed in both SignAds profiles, with facade photographs.','Share elevations or a clear site photo, approximate dimensions and any landlord requirements. The panel specification, supporting structure and installation scope need confirmation.']),
product('dimensional-letters','Dimensional letters','Signage','Give your brand depth, texture and a place in the room.','hero-signage',['Letter height','Metal or PU colour preference','Indoor or outdoor placement','Illumination preference'],['The profiles document metal lettering and PU colour letters across storefront and interior settings.','Start with your logo artwork and a photograph of the intended surface. The material, depth, finish and fixing method can then be discussed for that setting.']),
product('glow-signs','Glow signs','Signage','A bright, readable face for your everyday presence.','bank-signage',['Overall dimensions','Single or double sided','Existing frame details','Lighting and power access'],['Backlit glow boards are listed and illustrated in the profiles. A clear sign face can help a location stay visible in changing light.','Share the sign location and any existing frame details. Construction, lighting and installation are confirmed after the requirements are reviewed.']),
product('vehicle-branding','Vehicle branding','Outdoor','Take your message beyond a single address.','vehicle-branding',['Vehicle type and count','Photographs of each side','Operating locations','Campaign dates'],['The profiles cover canter/tempo, autorickshaw and bus advertising. Tell us which vehicle format you are considering and where the campaign is intended to run.','Vehicle dimensions, usable surfaces, placement permissions and campaign requirements will shape the proposal. Coverage and media availability must be confirmed.']),
product('hoardings','Hoardings','Outdoor','Think at street scale. Make the message easy to take in.','outdoor-branding',['Preferred locations','Display dimensions','Campaign period','Existing media booking'],['Hoardings and advertising banners are listed in the profiles. Start your enquiry with the intended location, campaign period and whether you already have a placement.','Media availability, permissions, structure and execution scope are discussed individually. No location availability or campaign reach is implied.']),
product('wayfinding','Safety & wayfinding','Signage','Help people find their way and understand the space.','wayfinding',['Sign schedule','Languages','Viewing distances','Site or floor plan'],['Safety and directional signage is documented in both profiles. Useful wayfinding begins with the routes people actually take through a site.','Share a floor plan, destination list, language needs and any applicable project specifications. Compliance and installation requirements must be reviewed for the actual site.']),
project('reception-lettering','An entrance with presence','Dimensional letters','hero-signage','profile-1-p05-02','Property','Reception wall','Illuminated lettering against a dark, geometric reception wall.',['dimensional-letters']),
project('restaurant-day-night','One storefront. Two moods.','LED signboards','restaurant-night','profile-1-p05-06','Hospitality','Storefront','A restaurant fascia photographed in daylight and after dark.',['led-signboards','dimensional-letters'],['restaurant-day','restaurant-night']),
project('jewellery-storefront','A more distinctive storefront','Metal letters','metal-letters','profile-1-p06-02','Retail','Storefront','Warm illuminated metal lettering above a jewellery shop entrance.',['dimensional-letters','led-signboards']),
project('office-reception','The first impression, indoors','Dimensional letters','reception','profile-1-p05-04','Office','Reception wall','Halo-lit dark lettering on an interior wall.',['dimensional-letters']),
project('backlit-fascia','Visibility around the corner','Glow signs','bank-signage','profile-1-p07-04','Banking','Storefront','An illuminated fascia extending around the corner of a building.',['glow-signs']),
project('building-identity','An identity at building scale','Building signage','building-signage','profile-1-p08-02','Property','Building exterior','Illuminated building identification photographed at night.',['led-signboards','dimensional-letters']),
project('directional-signage','Clarity at every turn','Wayfinding','wayfinding','profile-1-p09-03','Infrastructure','Directional signage','Bilingual directional panels shown in the profile.',['wayfinding']),
project('branded-interior','The room becomes the message','Interior branding','interior-branding','profile-1-p10-04','Office','Interior wall','A typographic wall application in a commercial interior.',['dimensional-letters','banners']),
project('campaign-display','A continuous street presence','Outdoor branding','outdoor-branding','profile-1-p10-05','Retail','Outdoor display','A sequence of illuminated outdoor advertising panels.',['hoardings','glow-signs']),
project('tempo-campaign','A message on the move','Vehicle branding','vehicle-branding','profile-1-p13-04','Property','Vehicle','Campaign graphics displayed on a tempo.',['vehicle-branding']),
project('bus-campaign','Branding beyond the storefront','Transit advertising','bus-branding','profile-1-p17-04','Healthcare','Vehicle','A bus-side campaign application from the profile.',['vehicle-branding'])
];
const guides=[
{id:'artwork-checklist',title:'A better file makes a better start.',description:'A practical checklist for sharing print and signage artwork.',image:'print-study',body:['Start with the final wording. Check names, telephone numbers, addresses and spelling before you share the file.','For logos, a vector PDF, SVG or original design file usually preserves clean edges at different sizes. Include linked images and the fonts or an outlined copy.','Tell us the intended finished dimensions and viewing distance. Avoid enlarging small images to fill a large sign.','Bleed, safe areas, colour profiles and production marks depend on the chosen product. Ask for the confirmed specification before final export.','Keep an editable original and send a clearly named review PDF alongside it. Final production approval and any design work should be agreed in the quote.'],details:['Check every contact detail','Include intended dimensions','Share the original artwork','Confirm export requirements']},
{id:'choosing-a-sign',title:'What kind of sign fits your space?',description:'Start with the surface, the viewing distance and the light.',image:'letter-study',body:['A reception wall, a street-facing shop and a building facade ask different things of a sign. Start by describing who needs to see it and where they will be standing.','Photograph the wall straight on and from the normal approach. Include obstacles, existing fixtures and any restrictions.','Consider the sign in daylight and after dark. Illumination, contrast and letter size should be discussed together.','Share the logo, approximate dimensions and the preferred finish. A site-specific specification is more useful than choosing a material from a photograph alone.'],details:['Viewing distance','Available surface','Day and night conditions','Logo proportions']},
{id:'planning-a-store-launch',title:'A store launch, from window to takeaway.',description:'Plan the physical touchpoints people encounter around your new space.',image:'restaurant-day',body:['Map the journey from the street to the counter. List the places where a customer needs to recognise the brand or understand what to do next.','Your brief might include a main sign, window graphics, directional panels and printed materials. Keep dimensions and artwork versions together.','Record landlord permissions, power access and site readiness. Share the intended opening date so feasibility can be discussed.','Group quantities by location and ask for a confirmed scope before production. This guide is a planning resource, not a claim of a completed turnkey launch.'],details:['List every touchpoint','Collect site photographs','Gather permissions','Confirm project scope']},
{id:'dimensional-letter-materials',title:'Depth changes the way a brand feels.',description:'An introduction to lettering, finish and illumination.',image:'letter-study',body:['Dimensional lettering gives a logo physical depth. Its appearance comes from the face, side return, surface finish and the way light falls around it.','The SignAds profiles list metal letters and PU colour letters. The available metal, coating and lighting details must be specified for each project.','An illuminated letter can be discussed in terms of face lighting or a halo effect. The generated material study on this page is illustrative and does not describe a guaranteed fabrication method.','Ask for the material, dimensions, fixing approach and lighting requirements to be documented in the quote.'],details:['Face and side return','Surface finish','Illumination','Fixing surface']}
];
baseContent.push(...guides.map(g=>({...g,kind:'guide' as const,eyebrow:'Ideas & guides',category:'Planning',related:[],status:'published' as const})));
export const solutions=[
{id:'new-store-launch',title:'New store launch',description:'Make a clear first impression, from the shopfront to the first takeaway.',services:['led-signboards','visiting-cards','flyers-pamphlets','banners'],project:'restaurant-day-night',considerations:['Opening date and site readiness','Main fascia, window and counter touchpoints','Artwork versions and landlord requirements']},
{id:'retail-showrooms',title:'Retail & showrooms',description:'Connect the outside of your store with the experience inside.',services:['acp-cladding','dimensional-letters','glow-signs','banners'],project:'jewellery-storefront',considerations:['Customer approach and sightlines','Fascia dimensions and lighting','Product and promotional areas']},
{id:'offices-receptions',title:'Offices & receptions',description:'Create a welcoming arrival and a space that feels like your brand.',services:['dimensional-letters','wayfinding','brochures'],project:'office-reception',considerations:['Reception wall and available surfaces','Visitor routes and room naming','Interior finish and lighting references']},
{id:'real-estate',title:'Real estate & buildings',description:'Help a site, building or sales space establish its presence.',services:['led-signboards','hoardings','banners','brochures'],project:'building-identity',considerations:['Building and site identification','Access, dimensions and placement permissions','Sales-office and printed information needs']},
{id:'events-exhibitions',title:'Events & exhibitions',description:'Plan the printed and physical touchpoints of your event.',services:['banners','brochures','flyers-pamphlets','wayfinding'],project:'',considerations:['Venue rules and setup access','Dates, display sizes and quantities','Directional information and takeaways']},
{id:'hospitality',title:'Restaurants & cafés',description:'Set the tone before guests walk through the door.',services:['led-signboards','dimensional-letters','glow-signs','flyers-pamphlets'],project:'restaurant-day-night',considerations:['Daytime and evening appearance','Storefront, entrance and internal touchpoints','Brand colours, logo and menu information']},
{id:'vehicle-transit',title:'Vehicle & transit campaigns',description:'Explore formats that take a campaign into everyday journeys.',services:['vehicle-branding','hoardings','banners'],project:'tempo-campaign',considerations:['Vehicle type, count and surface dimensions','Intended locations and campaign dates','Placement permissions and artwork adaptations']},
{id:'safety-directional',title:'Safety & directional signage',description:'Bring clear information to the routes people use.',services:['wayfinding','dimensional-letters'],project:'directional-signage',considerations:['Site plan and list of destinations','Languages and viewing distances','Project-specific safety requirements']}
];
export const imageUrl=(name:string)=>name.startsWith('/')?name:`/images/${name}.webp`;
export const hrefFor=(item:Content)=>`/${item.kind==='product'?'services':item.kind==='project'?'work':'ideas'}/${item.id}`;
