import {WorkExperience} from '@/components/work-experience';
import Link from 'next/link';
import {notFound} from 'next/navigation';
import {CategoryPage,ProductPage,JournalPage,GuidePage,SolutionsPage,SolutionPage,AboutPage} from '@/components/editorial-pages';
import {ServiceIndex} from '@/components/service-index';
import type {Metadata} from 'next';
import {ArrowUpRight,ArrowLeft,Phone,Mail,MessageCircle,Check} from 'lucide-react';
import {getPublishedContent} from '@/lib/store';
import {Content,solutions,imageUrl,hrefFor} from '@/lib/content';
import {ContentCard,QuoteBand} from '@/components/content-cards';
import {Portfolio} from '@/components/portfolio';
import {QuoteForm} from '@/components/quote-form';
import {MaterialVideo,DayNight,Reveal} from '@/components/motion';
export const dynamic='force-dynamic';
type Props={params:Promise<{slug:string[]}>;searchParams:Promise<Record<string,string|undefined>>};
const titles:Partial<Record<string,[string,string]>>={'print-products':['Print products','Enquire about visiting cards, flyers, brochures and banners. Explore print formats and share your artwork.'],'signage':['Signage & fabrication','LED signs, ACP cladding, dimensional letters, glow signs and wayfinding. Plan your next SignAds project.'],'outdoor':['Outdoor & transit advertising','Discuss hoardings, vehicle branding, bus advertising and outdoor campaign formats with SignAds.'],'work':['Our work','Explore photographs from the SignAds profiles, filtered by service, industry and application.'],'solutions':['Solutions for your business','Plan the print and signage for stores, offices, buildings, hospitality and campaigns.'],'enterprise':['For enterprise & agencies','A structured starting point for bulk print, store branding, office signage, fleet and campaign requirements.'],'ideas':['Ideas & guides','Practical guides to print artwork, signage materials and planning physical brand projects.'],'about':['About SignAds','Print, signage, fabrication and outdoor advertising for brands in physical spaces.'],'contact':['Get a quote','Tell SignAds about your print, signage or advertising project. Share dimensions, quantity, location and artwork.'],'privacy':['Privacy & artwork','How information and artwork submitted through the SignAds enquiry form are used.']};
export async function generateMetadata({params}:Props):Promise<Metadata>{const {slug}=await params;const key=slug.join('/');const record=titles[key]||(await getPublishedContent()).find(c=>hrefFor(c)==='/'+key);if(Array.isArray(record))return {title:record[0],description:record[1]};if(record)return {title:record.title,description:record.description};const sol=solutions.find(s=>key==='solutions/'+s.id);return {title:sol?.title||'Page not found',description:sol?.description}}
function Intro({eyebrow,title,description,children}:{eyebrow:string;title:string;description:string;children?:React.ReactNode}){return <section className="page-intro wrap"><p className="eyebrow">{eyebrow}</p><h1>{title.split('<br/>').map((line,i)=><span key={i}>{i>0&&<br/>}{line}</span>)}</h1><div className="intro-bottom"><p>{description}</p>{children}</div></section>}
export default async function Page({params,searchParams}:Props){const {slug}=await params;const key=slug.join('/');const query=await searchParams;const all=await getPublishedContent();const products=all.filter(c=>c.kind==='product');const projects=all.filter(c=>c.kind==='project');const guides=all.filter(c=>c.kind==='guide');
if(['print-products','signage','outdoor'].includes(key))return <CategoryPage category={key} products={products}/>;
if(key==='work')return <WorkExperience items={projects}/>;
if(key==='solutions')return <SolutionsPage/>;
if(key.startsWith('solutions/')){const solution=solutions.find(s=>s.id===slug[1]);if(!solution)notFound();return <SolutionPage solution={solution} products={products} projects={projects}/>;}
if(key==='enterprise')return <main id="main"><section className="enterprise-hero"><div className="wrap"><p className="eyebrow">Enterprise & agencies</p><h1>Bring the<br/>bigger picture.</h1><div className="intro-bottom"><p>Bulk print. Store branding. Office signage. Fleet and campaign requirements. Bring the moving parts into one clear brief.</p><a href="#enterprise-brief" className="button">Start your project brief <ArrowUpRight size={19}/></a></div></div></section><section className="section wrap"><div className="section-heading"><p className="eyebrow">A conversation built around scope</p><h2>Many requirements.<br/>A useful starting point.</h2><p>We can discuss these project types. Locations, quantities, installation requirements and schedules are reviewed individually.</p></div><div className="enterprise-categories">{['Bulk print & brand collateral','Store & showroom branding','Office & reception signage','Fleet & transit campaigns','Outdoor advertising requirements'].map((t,i)=><div key={t}><span>0{i+1}</span><h3>{t}</h3></div>)}</div></section><section id="enterprise-brief" className="quote-section"><div className="wrap quote-layout"><div><p className="eyebrow">The brief</p><h2>Let’s scope<br/>what’s next.</h2><p>Include the number of sites or units, the locations and the timeline. Share brand guidelines or a reference file if available.</p><p className="muted">Coverage, capacity, production dates and installation arrangements are confirmed for each project.</p></div><QuoteForm enterprise service="Enterprise & agency brief"/></div></section></main>;
if(key==='ideas')return <JournalPage guides={guides}/>;
if(key==='about')return <AboutPage/>;
if(key==='contact')return <main id="main"><section className="quote-section contact-section"><div className="wrap quote-layout"><div className="contact-copy"><p className="eyebrow">Let’s make it visible</p><h1>Good things<br/>start with<br/>a conversation.</h1><p>One product or a bigger brief.<br/>Tell us what you have in mind.</p><div className="contact-options"><a href="tel:+919152900157"><Phone size={20}/><span><small>Call SignAds</small>+91 91529 00157</span><ArrowUpRight size={18}/></a><a href="mailto:signadsindia@gmail.com"><Mail size={20}/><span><small>Email your brief</small>signadsindia@gmail.com</span><ArrowUpRight size={18}/></a><a href="https://wa.me/919152900157" target="_blank" rel="noreferrer"><MessageCircle size={20}/><span><small>Start a chat</small>Talk on WhatsApp</span><ArrowUpRight size={18}/></a></div><p className="contact-hint">Working across several sites or formats? <Link href="/enterprise#enterprise-brief">Use the enterprise brief ↗</Link></p></div><QuoteForm service={query.service||''}/></div></section></main>;
if(key==='privacy')return <main id="main"><Intro eyebrow="Your information" title="Privacy & artwork." description="A clear explanation of what happens when you send an enquiry."/><article className="prose legal wrap"><h2>What the form collects</h2><p>Your contact information, company, project requirements and any file you choose to attach are saved so the SignAds team can review your enquiry. The form does not take payment or place an order.</p><h2>How it is used</h2><p>Submitted details are used to understand your requirements and respond to you. Artwork is supplied for project discussion; uploading it does not give permission to publish it in a portfolio or reuse it for other customers.</p><h2>Access and storage</h2><p>Enquiries and uploaded artwork are held in a private team inbox. Access is restricted to authorised team accounts. Uploaded enquiry files are not served as public portfolio assets.</p><h2>Your choices</h2><p>Only upload files you are authorised to share. You can ask about your enquiry, request correction or request deletion by emailing <a href="mailto:signadsindia@gmail.com">signadsindia@gmail.com</a> with your enquiry reference. A fixed retention period has not yet been published.</p><h2>External contact links</h2><p>Phone and email links open your chosen application. The WhatsApp link opens WhatsApp, which has its own privacy terms. This site does not require marketing consent to submit a quote enquiry.</p></article></main>;
const item=all.find(c=>hrefFor(c)==='/'+key);if(!item)notFound();const related=products.filter(p=>item.related.includes(p.id));if(item.kind==='project')return <main id="main"><section className="project-intro wrap"><Link href="/work" className="back-link"><ArrowLeft size={16}/> Back to the work</Link><p className="eyebrow">{item.category} / {item.industry}</p><h1>{item.title}</h1><p>{item.description}</p></section><section className="project-detail-image wrap">{item.id==='restaurant-day-night'?<DayNight/>:<img src={imageUrl(item.image)} alt={item.description} width="1040" height="780"/>}</section><section className="section wrap two-column"><div><p className="eyebrow">Project notes</p><h2>The application,<br/>up close.</h2></div><div className="prose">{item.body.map(p=><p key={p}>{p}</p>)}<dl className="project-facts"><div><dt>Service</dt><dd>{item.category}</dd></div><div><dt>Application</dt><dd>{item.application}</dd></div>{item.location&&<div><dt>Location</dt><dd>{item.location}</dd></div>}{item.clientName&&item.clientApproved&&<div><dt>Client</dt><dd>{item.clientName}</dd></div>}<div><dt>Source</dt><dd>SignAds company profile</dd></div></dl><p className="muted">For a similar project, share your site details and requirements. Materials and installation specifications are confirmed in your quote.</p></div></section>{related.length>0&&<section className="section wrap compact-top"><div className="section-heading"><p className="eyebrow">Explore related services</p><h2>Make it your own.</h2></div><ServiceIndex items={related}/></section>}<QuoteBand service={item.category}/></main>;
if(item.kind==='guide')return <GuidePage item={item}/>;
return <ProductPage item={item} projects={projects}/>;}
