import fs from 'node:fs/promises';
const base='http://localhost:5173';const admin={Cookie:'__sites_local_auth=1'};const results=[];
async function test(name,fn){try{const detail=await fn();results.push({name,passed:true,detail})}catch(e){results.push({name,passed:false,error:String(e)})}}
function assert(v,m){if(!v)throw new Error(m)}
await test('Private CMS rejects anonymous access',async()=>{const r=await fetch(base+'/api/admin');assert(r.status===403,r.status);return r.status});
await test('Private source asset rejects anonymous access',async()=>{const r=await fetch(base+'/api/media/profile-1-p03-02');assert(r.status===404,r.status);return r.status});
await test('Authorised source asset loads',async()=>{const r=await fetch(base+'/api/media/profile-1-p03-02',{headers:admin});assert(r.status===200,r.status);assert(r.headers.get('content-type')==='image/webp','not an image');return (await r.arrayBuffer()).byteLength});
function form(key=crypto.randomUUID()){const f=new FormData();Object.entries({name:'QA API test',email:'qa@example.invalid',phone:'9999999999',location:'QA only',service:'Visiting cards',quantity:'100',installation:'No',artwork:'Ready to print',consent:'true',enterprise:'false',requestKey:key}).forEach(([k,v])=>f.set(k,v));return f}
await test('Invalid fields return helpful validation',async()=>{const f=form();f.set('email','not-email');const r=await fetch(base+'/api/enquiries',{method:'POST',body:f});const d=await r.json();assert(r.status===400&&d.fields.email,JSON.stringify(d));return d.fields});
await test('Foreign origin rejected',async()=>{const r=await fetch(base+'/api/enquiries',{method:'POST',headers:{Origin:'https://untrusted.invalid'},body:form()});assert(r.status===403,r.status);return r.status});
await test('Disguised artwork file rejected',async()=>{const f=form();f.set('artworkFile',new Blob(['this is not a PDF'],{type:'application/pdf'}),'fake.pdf');const r=await fetch(base+'/api/enquiries',{method:'POST',body:f});assert(r.status===400,r.status);return (await r.json()).error});
await test('Artwork saved privately and retry is idempotent',async()=>{const key=crypto.randomUUID();const f=form(key);f.set('artworkFile',new Blob([await fs.readFile('public/images/print-study.webp')],{type:'image/webp'}),'qa-artwork.webp');const r=await fetch(base+'/api/enquiries',{method:'POST',body:f});const d=await r.json();assert(r.status===201,JSON.stringify(d));const retry=await fetch(base+'/api/enquiries',{method:'POST',body:form(key)});assert((await retry.json()).id===d.id,'duplicate id');const anonymous=await fetch(base+'/api/media/'+d.id);assert(anonymous.status===404,'artwork exposed');const download=await fetch(base+'/api/media/'+d.id,{headers:admin});assert(download.status===200,'download failed');return {id:d.id,private:true,downloadBytes:(await download.arrayBuffer()).byteLength}});
const content={id:'qa-content-check',kind:'guide',title:'QA content check',eyebrow:'QA',description:'Temporary test record',category:'Planning',image:'print-study',body:['QA only.'],details:[],related:[],status:'draft'};
async function save(type,data){return fetch(base+'/api/admin',{method:'POST',headers:{...admin,'Content-Type':'application/json'},body:JSON.stringify({type,data})})}
await test('CMS draft and publishing persist',async()=>{let r=await save('content',content);assert(r.ok,await r.text());r=await fetch(base+'/ideas/qa-content-check');assert(r.status===404,'draft publicly visible');r=await save('content',{...content,status:'published'});assert(r.ok,await r.text());r=await fetch(base+'/ideas/qa-content-check');assert(r.status===200,'published page missing');return 'draft 404, published 200'});
await test('Generated image cannot become completed project',async()=>{const r=await save('content',{...content,id:'qa-invalid-project',kind:'project',image:'letter-study',status:'published'});assert(r.status===400,'generated project accepted');return (await r.json()).error});
await test('Pending permission cannot enable a named client',async()=>{const r=await save('content',{...content,id:'qa-invalid-client',clientName:'Unapproved name',clientApproved:true,rightsStatus:'permission-pending'});assert(r.status===400,'client approval bypass');return (await r.json()).error});
await fs.writeFile('outputs/api-qa-results.json',JSON.stringify(results,null,2));console.log(JSON.stringify(results,null,2));if(results.some(r=>!r.passed))process.exitCode=1;
