import json,csv
from pathlib import Path
assets=json.loads(Path('research/image-inventory-raw.json').read_text())
names={3:['Shubham Caterers','Shubham Caterers','Patharecha Mahaganpati (visible Marathi text)','Patharecha Mahaganpati (visible Marathi text)','Turde Wine Centre'],4:['vivo (visible brand)','Multiple names; not reliably legible','Not legible','Anmol Electronics'],5:['Neelkanth Luxuria','Sukhad Home','navio','Yashoda','Sukhad Home'],6:['Aabhushan','Yashoda Hospital','Gehana','Maheshwari Jewellers','Aabhushan'],7:['CSB Bank','HDFC Bank','CSB Bank','IndusInd Bank'],8:['Gurukrupa Realcon','Gaurav Lords','Gaurav Lords','Not legible','Rajasthan Bhavan'],9:['6J (zone marker)','CIDCO','No commercial name','No commercial name','Customs'],10:['TESCON','Laptop World','No commercial name','GAV / campaign text partially legible'],11:['Dentist (generic)','Multiple signs; not reliably legible','TESCON','Dentist (generic)'],12:['Outdoor Advertising (generic)','Not reliably legible','Paragon','Hyundai Eon'],13:['Not reliably legible','GIVA','Not reliably legible','Not reliably legible'],14:['MPC (visible)','Polaris Hospital','MedPlus','Not reliably legible'],15:['Not reliably legible','Kidz N Kidz','Not legible','Not reliably legible'],16:['MOC','Street OG / TVS','Street OG / TVS','MOC'],17:['Not reliably legible','Al Baik','Dr Agarwals','Dr Agarwals','Dr Agarwals','Not reliably legible'],18:['Generic display mockup','Generic display mockup','Generic display mockup','NEOYON / reference collage'],19:['Disha Computer Institute','Potato','Porter','Ajeya','SkoolEase'],20:['Not reliably legible','Not reliably legible'],21:['Not reliably legible','Not reliably legible','Bata','Multiple names; not reliably legible'],22:['Generic printing collage','Generic stationery mockup']}
public={'profile-1-p05-02':'hero-signage','profile-1-p05-03':'restaurant-day','profile-1-p05-06':'restaurant-night','profile-1-p05-04':'reception','profile-1-p06-02':'metal-letters','profile-1-p07-04':'bank-signage','profile-1-p08-02':'building-signage','profile-1-p09-03':'wayfinding','profile-1-p10-04':'interior-branding','profile-1-p10-05':'outdoor-branding','profile-1-p13-04':'vehicle-branding','profile-1-p17-04':'bus-branding','profile-1-p04-03':'acp-cladding','profile-1-p11-05':'projecting-sign'}
for a in assets:
 p=a['page'];i=int(a['id'].split('-')[-1])-2;a['visibleName']=names.get(p,[])[i] if p in names and 0<=i<len(names[p]) else ('SignAds' if p in [1,23] else 'Not applicable')
 a['category']=a['category'].replace('*','').strip() or ('Brand identity' if a['width']>a['height']*3 else 'Profile background')
 a['industry']='Hospitality' if p==5 and i in [1,4] else 'Retail' if p in [3,6] else 'Banking' if p==7 else 'Property' if p==8 else 'Unknown'
 a['application']=a['category'];a['date']=None;a['location']=None;a['orientation']='landscape' if a['width']>a['height'] else 'portrait'
 a['quality']='large-card' if a['width']>=1000 else 'small-card' if a['width']>=600 else 'thumbnail-only'
 a['origin']='reference-image' if p in [12,18,22] else 'pdf-extraction'
 a['use']='Internal reference only; authorship unverified' if p in [12,18,22] else 'Internal brand/reference asset' if p in [1,23] else 'Portfolio candidate; request original for prominent use'
 a['clientApproved']=False;a['rightsNote']='Photograph supplied in business profile. Named-client endorsement and public-display approval require confirmation.';a['caption']=a['category'];a['alt']=a['category']+' from the supplied SignAds profile';a['project']=None
 a['publicUrl']='/images/'+public[a['id']]+'.webp' if a['id'] in public else None
 a['appearsOn']=['/work'] if a['id'] in public else []
 if a['id']=='profile-1-p05-02':a['appearsOn']=['/','/signage','/work/reception-lettering']
 a['storageKey']='source/'+a['id']+'.jpg';a['sourceRecords']=[{'file':a['source'],'page':a['page']}]+a['alsoOn']
 a['permissionRequired']=a['page'] not in [1,23]
for name,title in [('print-study','Paper and print material study'),('letter-study','Illuminated dimensional letter study')]:
 assets.append({'id':name,'source':'Generated for SignAds on 2026-09-17','page':None,'width':1536 if name=='print-study' else 1672,'height':1024 if name=='print-study' else 941,'path':'research/source-images/'+name+'.png','category':'Illustration','industry':'General','application':'Category hero','date':'2026-09-17','location':None,'orientation':'landscape','quality':'hero','rightsStatus':'illustrative','rightsNote':'AI-generated supporting image. Not a completed project.','origin':'ai-generated','visibleName':'None','clientApproved':False,'caption':title,'alt':title+'; illustrative','publicUrl':'/images/'+name+'.webp','appearsOn':['/','/print-products' if name=='print-study' else '/signage'],'storageKey':'source/'+name+'.png','use':'Supporting category image and silent video loop','permissionRequired':False})
Path('lib/asset-catalog.json').write_text(json.dumps(assets,indent=2))
Path('research/image-inventory.json').write_text(json.dumps(assets,indent=2))
with open('research/image-inventory.csv','w') as f:
 fields=['id','source','page','category','visibleName','width','height','quality','use','rightsStatus','permissionRequired','origin','location','date'];w=csv.DictWriter(f,fieldnames=fields,extrasaction='ignore');w.writeheader();w.writerows(assets)
print(len(assets),'catalogued assets')
